name = "live"
type = "javascript"

# 请修改成自己的 account_id
account_id = "account_id"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-4-8"

# 请修改成自己的 KV 数据库 ID
[[kv_namespaces]]
binding = "OIERLIVE"
id = "kv_id"